puddletag/puddletag

- source/puddlestuff/mainwin/funcs.py
padding of total tracks number should follow the same rules as padding of a track number i.e. 01/07 instead of 01/7
> Padding of total tracks number

- README.rst
- source/create_macos_app_bundle.sh
Recently I wrote a homebrew formula for puddletag. This was accepted and now puddletag can be install via "brew install puddletag".
I added the comments in the readme.
For a better user experience I also added a script for creating a MacOS Bundle under OS X. This allows for using puddletag on MacOS as a click and run app. A MacOS Bundle is similar to the puddletag.desktop file. The file will be run by the formula on homebrew to create the app bundle. The homebrew maintainers those routine have to be included in upstream products, like puddletag,
I will really appreciate it a lot, if you add these changes into your repo. Puddletag is really a great tool replacing mp3tag on non Windows systems. It is even better than iTunes. That's why the Mac World should be able to use it!
For any changes …
> Puddletag for Homebrew

- source/puddlestuff/audioinfo/_compatid3.py
This one fix an import error i get with latest python-mutagen 1.34.999+1301~0c8997f-0~ppa0~trusty from https://launchpad.net/~lazka/+archive/ubuntu/dumpingplace
> Fix for BitPaddedInt import error

- source/puddlestuff/audio_filter.py
Added a Matches keyword to the filter that support regular expressions.
Addressing issue #329.
Needs some scrutiny, from more experienced eyes, and if accepted documentation.
I have used it with this filter:
__filename MATCHES "^\d - \d\d"
to great satisfaction (what I wrote it for in fact ;-).
> Filter: Matches

- source/puddlestuff/util.py
Add shutil.move function as fail-back for method for events where os.rename fails.  when the source and destination are not the same volume, the os.rename function fails with "Invalid cross-device link" error.  This can occur when the tag pattern contains an absolute path
more info: http://puddletag.sourceforge.net/forum/viewtopic.php?f=3&t=274&p=1313#p1313
> Add shutil.move fail-back for os.rename

- source/puddlestuff/tagsources/amazon.py
Discovered when looking up data for https://www.amazon.com/dp/B000002JUC (missing artist name in one of the elments in the response led to KeyError: 'artist').
> Handle Amazon albums with no artist/album name

- _sources/download.txt
Add missing `python-configobj` package.
> Add missing package for installation from source

- source/puddlestuff/functions.py
1. Select at least 3 files (that aren't mp3)
2. Open Functions window and select 'Update From Tag'
3. Select ID3 from Tag dropdown and click OK
puddletag crashes with a `mutagen.mp3.HeaderNotFoundError`.
This adds a `except` statement to prevent this.
> Fix for Update From Tag function crash

- source/puddlestuff/masstag/dialogs.py
1. Open puddletag and open mass tagging panel
2. Click search without selecting a profile.
puddletag crashes with an:
`AttributeError: 'NoneType' object has no attribute 'file_pattern'`
This adds a type check to see if a profile has actually been loaded.
If not then it displays a message to remind the user to load one and returns None.
> Fix for masstagging search button crash

- source/puddlestuff/masstag/__init__.py
- source/puddlestuff/masstag/dialogs.py
Added type checking to merge_track (in source/puddlestuff/masstag/__init__.py)
to correct the original error, also added a type parameter to the
setpreview pyqtSignal (in source/puddlestuff/puddleobjects.py) to fix another
error that arose after fixing the first one.
Fixes #527
> Fix for TypeError crash when querying MusicBrainz for tag info

- source/puddlestuff/audioinfo/id3.py
Removed `str.encode()` calls from the `set_uslt` function in
`source/puddlestuff/audioinfo/id3.py`. The crashes were being
caused by an unnecessary conversion to bytes.
Fixes: #566
> Fix for crash when adding custom tag with language lyrics

- source/puddlestuff/mainwin/funcs.py
Removed conditional that resulted in information for
all tracks being shown when only the first track of the
list is selected. The conditional didn't seem to be necessary
as my testing (after removing it) didn't reveal any degraded
functionality/crashes.
Fixes #597
> Fix for extended tags view bug

- source/puddlestuff/tagsources/_acoustid.py
- source/puddlestuff/tagsources/acoust_id.py
Removed (seemingly) pointless `try`/`catch` that always
resulted in a `TypeError`. Also added `str` conversion in
`_fingerprint_file_fpcalc()` to avoid another error.
Fixes: #564
> Fix for crash when searching with AcoustId

- source/puddlestuff/mainwin/funcs.py
Adds a `try`/`except` statement to catch IndexError
in the circumstance described by issue #560.
Fixes: #560
> Fix for index error in action dialog

- source/puddlestuff/functions.py
Hi there,
this PR fixes the problem described in #391 where keyerrors are raised, when the autonumbering function is used.
Fixes #391
> Rewrite autonumbering function to fix #391.

- source/puddlestuff/functions.py
Line 904 in functions.py was opening the cover as a text file,
resulting in a TypeError (and crash).
This changes it from 'w' to 'w+b' (write bytes) removing the error and crash.
Fixes: #623
> Fix for crash when specifying 'Export artwork to file' in action

- source/puddlestuff/puddletag.py
- source/puddlestuff/tagmodel.py
- source/puddlestuff/util.py
Added import for MutagenError to catch the exception.
With these changes no tags are written to the file in the
event of a mutagen error, but the trace is still output to
the console.
~~A nice addition would be a dialog warning that the files are
read-only when trying to write tags. (I am not versed in PyQt,
otherwise I would do it myself.)~~
An error dialog is now displayed when a file has a permission error.
Fixes #546
Fixes #628
> Fix for read-only file crash

- source/puddlestuff/tagmodel.py
I encountered an issue with "Shift + Enter" not behaving equivalently to "Shift + Return" (Enter is located on the numeric keypad).
When the Shift + Enter is pressed both `Qt.ShiftModifier` and `Qt.KeypadModifier` modifiers are set, causing the current check for `events.modifiers() == Qt.ShiftModifier` to return False. This leads to the shift modifier being ignored. 
The fix implemented here is just to check that Qt.ShiftModifiers is among the modifiers that are set. An alternative solution if you want to rule out additional modifiers is to use something like:
```Python
if event.key() == Qt.Key_Return:
shift_pressed = event.modifiers() == Qt.ShiftModifier
else:
shift_pressed = event.modifiers() == Qt.ShiftModifier | Qt.KeypadModifier
if shift_pressed:
editor.returnPressed = SHIFT_RETURN …
```
> BUG: fix Shift+Enter behavior

- source/puddlestuff/actiondlg.py
- source/puddlestuff/puddleobjects.py
Adds a conditional check in the CreateAction class (line 566 - source/puddlestuff/actiondlg.py)
to disable the 'Edit' and 'Duplicate' buttons when there are no
functions in the action dialog.
Steps to reproduce:
1. Open actions dialog
2. Add a new action (don't add any functions at this point)
3. Push the pencil (edit) button or the duplicate button, instead of the plus (add) button
puddletag crashes with the traceback:
```sh
Traceback (most recent call last):
File "../puddletag/source/puddlestuff/actiondlg.py", line 659, in edit
self.win = CreateFunction(self.functions[self.listbox.currentRow()],
IndexError: list index out of range
launch.bash: line 3:  5969 Aborted                 (core dumped) PYTHONPATH=source/ ./source/puddletag
```
Adds a conditional check to the `moveDown` method …
> Fixes for action dialog crashes

- source/puddlestuff/plugins/view_all_fields/__init__.py
Added extra imports to correct error. 
It happens when puddletag is launched:
```python
puddletag Version: 2.0.0
Locale: en_US
[2020-09-16 13:15:19,025]ERROR:Failed to load plugin View All Fields; error=cannot import name 'add_config_widget' from 'puddlestuff' (/home/blue/projects/gh/puddletag-root/puddletag/source/puddlestuff/__init__.py)
Traceback (most recent call last):
File "/home/blue/projects/gh/puddletag-root/puddletag/source/puddlestuff/pluginloader.py", line 78, in load_plugins
module = import_module('puddlestuff.plugins.' + plugin[MODULE_NAME])
File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen …
```
> Fix for ImportError in View All Fields plugin

- source/puddlestuff/puddletag.py
- source/puddletag
- source/puddletag.1
This allows running from programs such as cmus which expect a tagger to
be able to accept more than one filename or directory name. It also
makes it more convenient to launch puddletag from the command line for
ad-hoc editing of several files. Previously puddletag would simply
ignore any non-option arguments after the first one.
> Accept multiple file/directory names on commandline

- source/puddlestuff/functions.py
When no separator parameter is provided for function *Split field using operator* (which happens when one deletes default content of a textbox), uncaught `ValueError` is thrown, resulting in the application shutdown.
The error is now caught and function returns unchanged parameter.
Resolves #641
> Fixed error with empty separator in split field function

- source/puddlestuff/tagmodel.py
When there are uncommited changes in preview mode and user presses
refresh by accident, all changes are lost. Now ask the user if he
wants to discard before triggering refresh
> Ask user to discard changes if previews are active when refreshing

- source/requirements.txt
Fixes one of the issues described in https://github.com/puddletag/puddletag/issues/666
> lxml package is needed by AllMusic TagSource

- source/puddlestuff/tagsources/amg.py
get_encoding returns a string describing the encoding. To overwrite page with that is a glaring bug. Moreover the BeautifulSoup parser doesn't even care about the encoding so we don't need to divine (or if it does it works it out for itself)..
Removing this one line makes the AllMusic tagsource functional once more.
Fixes: https://github.com/puddletag/puddletag/issues/666
> Fix bug in AllMusic tagsource

- source/puddlestuff/tagsources/__init__.py
This method leans on the html.parser module and that by specification only accepts strings:
https://docs.python.org/3/library/html.parser.html#html.parser.HTMLParser.feed
It cannot therefore be sensibly used to divine the encoding of a byte-string and this whole block of code is  redundant. Likely a carry over from the Python 2 to 3 conversion.
Moreover I can find no reference in nay documentation to a FoundEncoding exception and no idea where that is implemented but certainly not by html.parser.
> Fix tagsources get_encoding

- puddlestuff/tagsources/amg.py
- puddlestuff/tagsources/parse_html.py
The format of the AllMusic page has clearly changed a little since it was written:
- album  and artist are now in h1 and h2 tags not in div tags
- the class of the sidebar album container is no longer "album-contain" but "album-contain gallery-launch". For which the HTML parser needed a patch to support CSS class matching a la:
https://tanzu.vmware.com/content/blog/xpath-css-class-matching
- A clear bug remained in which album_page was overwrritten by an encoding
- Another bug existed in which a string was sought (.find) in a byte-string.
> The AllMusic tagsource was broken

- puddlestuff/tagsources/acoust_id.py
- puddlestuff/tagsources/amazon.py
- puddlestuff/tagsources/amg.py
- puddlestuff/tagsources/discogs.py
- puddlestuff/tagsources/example.py
- puddlestuff/tagsources/freedb.py
- puddlestuff/tagsources/mp3tag/__init__.py
- puddlestuff/tagsources/mp3tag/funcs.py
- puddlestuff/tagsources/mp3tag/parse_debug.py
- puddlestuff/tagsources/musicbrainz.py
I can now run one from the puddletag source dir with:
`PYTHONPATH=. python puddlestuff/tagsources/discogs.py`
which was clearly the intent at some point given they all have an:
`if __name__ == '__main__':`
block. But they could not run because of relative package imports. These have now been made explicit. Which is safe enough and and I see little reason to keep them relative while breaking the ability to debug tagsources outside of the threaded context of the UI.
> Make tagsource definition files runnable (again)

- puddlestuff/tagsources/TagSource.py
And provide a class from which tag sources should derive.
Assembling this raises some interesting questions about puddletags interface to tagsources and I suspect it can be improved significantly
Two areas of grave concern:
1. The `search()` method has a very bizarre interface that depends upon the definition of group_by. This should be standardised. Easy to do by fixing `webdb.py`.
2. The group_by attribute seems flexible but there are rather heavily hardcoded assumptions that it's first entry is "album" to my mind,  and the retrieve() method is always receiving the value of the tag that is the first entry in group_by. 
And areas of mild concern arise:
1. `TAGLIST` is unimplemented and no clue is easily found what was envisioned here.
2. `search` and `keyword_search` should really be one …
> An attempt to document the tagsource interface

- puddlestuff/puddletag.py
The default message is not 100% obvious that UTF8 encoding is required. This message is hopefully more verbose.
Previous pull request #660 tried to implement compatibility to latin9, but this was very obscure and does not help other encodings with the same issues.
> Explicit message for UnicodeError

- puddlestuff/audio_filter.py
The filter was broken since the Python v2->v3 migration because the name of the method for boolean evaluation changed, and as a result of that the parsed filter expression wasn't properly evaluated but always returned true for any input.
Also fixed a small related issue where un-parsable inputs resulted in a crash. These are now caught and fallback to the simple string search.
Fixes #638 and #665.
> Filter Fix

- puddlestuff/actiondlg.py
- puddlestuff/mainwin/storedtags.py
- puddlestuff/tagmodel.py
The `setValue` method now expects a int, but the division results in a
float. Since the value and the angleDelta are already integers, just do
a integer division instead.
I was thinking about just using `int()` to convert the float, but I
liked the integer division solution better.
Fixes #662
> Fix scrolling

- puddlestuff/audioinfo/id3.py
- puddlestuff/mainwin/storedtags.py
- puddlestuff/tagsources/musicbrainz.py
Through some python 2 migration confusion (str/unicode vs. bytes/str)
the handling of the ID3 UFID frames broke. As per the [spec](https://id3.org/id3v2.4.0-frames) (chapter 4.1), these
frames have a binary content (so not necessarily a string). Mutagen
passes the content correctly as `bytes`, but puddletag internally
handles it as a utf8-encoded string, so the id3 wrapper has to handle
the conversions in both directions. If the content should be non-utf8,
it will simply be ignored. This behaviour is not ideal, but I couldn't
think of a better one right now.
With the conversion working again, the stored tags window only gets
strings again, and puddletag does not crash.
This partially reverts commit c0504240a2b947da91c1e6549ba48040238d8460.
Fixes #590
Fixes #565
Fixes #595
I haven't pinned …
> MusicBrainz bugfixes

- puddlestuff/tagsources/discogs.py
After reviewing the API for tagsources it becomes clear that the only thing imported from any is the `info` attribute and that leaves three, seemingly legacy functions, polluting the discogs tagsource code. 
They have been removed, and a runtime test performed to rule out any oversights.
Sorry to be flooding you with PRs. But I am keeping them small, and as independent as possible for very simple review and merge.
> Removed unused functions

- puddlestuff/audioinfo/id3.py
The language of a USLT frame has to be a valid ISO 639-2 language code.
Instead of falling back to `XXX` which is invalid, use the proper `und`
(undefined).
Because of the way puddletag handles multi-value frames as a single
`|`-sepeared string, it is hard to do a proper validation in the gui.
The language is required for USLT and mutagen will complain harshly
with a crash when it is missing or too short (less than 3 chars). So
extend the fallback to also cover that case.
> Use valid fallback lang for id3 uslt

- puddlestuff/about.py
- puddlestuff/action_shortcuts.py
- puddlestuff/actiondlg.py
- puddlestuff/constants.py
- puddlestuff/duplicates/algwin.py
- puddlestuff/genres.py
- puddlestuff/helperwin.py
- puddlestuff/libraries/amarok.py
- puddlestuff/libraries/prokyon.py
- puddlestuff/libraries/quodlibetlib.py
- puddlestuff/m3u.py
- puddlestuff/mainwin/action_dialogs.py
- puddlestuff/mainwin/artwork.py
- puddlestuff/mainwin/dirview.py
- puddlestuff/mainwin/funcs.py
- puddlestuff/mainwin/logdialog.py
- puddlestuff/mainwin/patterncombo.py
- puddlestuff/mainwin/storedtags.py
- puddlestuff/mainwin/tagpanel.py
- puddlestuff/musiclib.py
- puddlestuff/pluginloader.py
- puddlestuff/plugins/view_all_fields/__init__.py
- puddlestuff/puddleobjects.py
- puddlestuff/puddlesettings.py
- puddlestuff/puddletag.py
- puddlestuff/releasewidget.py
- puddlestuff/shortcutsettings.py
- puddlestuff/tagmodel.py
- puddlestuff/webdb.py
- puddletag
Traditionally, enum members in Qt were not scoped to the enum itself but the parent of the enum. Take the enum [`Qt::AlignmentFlag`](https://doc.qt.io/qt-5/qt.html#AlignmentFlag-enum) as an example: Its member `AlignLeft` is in the same scope (the `Qt` namespace), and can be referenced by `Qt::AlignLeft` instead of `Qt::AlignmentFlag::AlignLeft`. This stems from the way enums are implemented in C/C++.
This changed recently starting in Qt itself, and now manifesting in PyQt in a major way. In PyQt4 and earlier versions of PyQt5, enum members were only accessible like in Qt with `Qt.AlignLeft`. Starting with PyQt v5.11, they are accessible with both `Qt.AlignLeft` and `Qt.AlignmentFlag.AlignLeft`. And [starting with PyQt6](https://www.riverbankcomputing.com/static/Docs/PyQt5/gotchas.html#enu …
> Use PyQt Scoped Enums

- puddlestuff/functions.py
Puddletag kept crashing when trying to select "Format Value" (Actions -> Actions / Quick Actions -> Add / Edit -> Add function -> Format Value).
Proposed PR appears to fix the issue.
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/puddlestuff/actiondlg.py", line 364, in showexample
>     val = apply_actions([self.func], audio, state, fields)
>   File "/usr/lib/python3.10/site-packages/puddlestuff/findfunc.py", line 620, in apply_actions
>     temp = func.runFunction(val, audio, state, None, r_tags)
>   File "/usr/lib/python3.10/site-packages/puddlestuff/findfunc.py", line 870, in runFunction
>     return func(**topass)
>   File "/usr/lib/python3.10/site-packages/puddlestuff/functions.py", line 204, in formatValue
>     ret = findfunc.parsefunc(p_pattern, …
> Fix crashes on 'Format value'

- puddlestuff/plugins/view_all_fields/__init__.py
- puddlestuff/tagmodel.py
When column layout changes, take a snapshot of the current column
sizes and apply them to the new layout. Columns are matched by their
name/title, so two columns with the same name/title will both get the
same size of the previously rightmost one of them. Hidden columns have
a size of 0, so be sure to ignore them, elsewise un-hiding won't work.
For obvious reasons, this only applies if puddletag is not configured
to autoresize the columns.
This change has a (IMHO nice) side effect: When you switch from
autoresize to not-autoresize, the columns will retain their last
(autoresized) size and can be manually resized from there.
Plus some minor refactoring/cleanup.
Fixes #640
> Preserve column sizes

- puddlestuff/actiondlg.py
- puddlestuff/helperwin.py
- puddlestuff/libraries/quodlibetlib.py
- puddlestuff/m3u.py
- puddlestuff/mainwin/artwork.py
- puddlestuff/mainwin/dirview.py
- puddlestuff/mainwin/filterwin.py
- puddlestuff/puddleobjects.py
- puddlestuff/puddletag.py
- puddlestuff/tagmodel.py
As with every major/minor release, Qt5 and subsequently PyQt5 obsoleted/deprecated a few things (classes, methods, properties, ...) which will be removed with Qt6 and PyQt6. This PR replaces all these obsoleted/deprecated things with their "modern" pendant to future-proof, and preempt instant breakage when moving to PyQt6.
> Replace obsolete PyQt5 things

- puddlestuff/__init__.py
- puddlestuff/about.py
With 7f1fa4f2 the `puddlestuff` package was moved and as a result its
relative path/position to the git root changed. The changeset detection
has been updated to accommodate the new location.
And since I was at it, also replaced the usage of hardcoded `/` with
`os.path.join()`, and changed from the `master` branch to `HEAD` which
always points to the current commit. The downside is that `HEAD` can
contain references, but the upside is that it now also works for tags
and all other commits.
This solution does not require deps like `gitpython` or assumes the
`git` command is avilable (though that would be resonable).
Moved the library versions to its own tab, so we have more space for
more and it can be easily copied. And moved the version logic into a
separate function, in the hope we can …
> About dialogue improvements

- puddlestuff/shortcutsettings.py
When changing shortcuts in the settings dialogue, it crashes because of some int vs. float mismatches, which are fixed by explicitly using the float variants/signatures. Also fixed the text representation which is displayed.
> Fix shortcut settings

- README.md
- puddlestuff/mainwin/filterwin.py
Restore the unintentionally broken backwards-compatibility for Qt 5.12, which was the last LTS version. I double-checked #705, and this was the only breaking change.
> Restore Qt5 LTS compatibility

- puddlestuff/puddleobjects.py
See [my comment in #648](https://github.com/puddletag/puddletag/issues/648#issuecomment-1065782439) for a full explanation.
Fixes #648.
> Remove ghost window

- translations/puddletag_de.ts
Just some missing german translations. I also tried to call "python3 update_translation.py de" but it threw an error.
```
QIODevice::read (QFile, ":/caseconversion.action"): device not open
QIODevice::read (QFile, ":/standard.action"): device not open
Traceback (most recent call last):
File "/opt/Puddletag/puddletag/update_translation.py", line 147, in <module>
f.seek(-len(line), 1)
io.UnsupportedOperation: can't do nonzero cur-relative seeks
```
> Some german translations

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- puddlestuff/puddletag.py
Add two purpose-build templates for bug reports and feature request. Those will hopefully give users some handrails and structure to improve issue quality. They are based on the default that GitHub provides, but extended/reworded to fit better.
I am deliberately not using the markdown templates but the [new yaml-based issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). While they are still in beta, they have the distinct advantage of being more flexible and allow better structure, and also make it possible to pre-fill the separate parts individually with [query parameters](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creat …
> Report problems from the app

- puddlestuff/findfunc.py
- puddlestuff/funcprint.py
- puddlestuff/functions.py
- puddlestuff/masstag/dialogs.py
- puddlestuff/puddleobjects.py
- puddlestuff/tagmodel.py
- puddlestuff/tagsources/__init__.py
- puddlestuff/tagsources/amazon.py
- puddlestuff/tagsources/amg.py
- puddlestuff/tagsources/mp3tag/__init__.py
- puddlestuff/tagsources/mp3tag/funcs.py
- puddlestuff/translations.py
- puddlestuff/webdb.py
In support of the ongoing adoption of Unicode within Python, [bug # 27364
(2016)][1] deprecates "invalid" (read: regular expression) escape
sequences outside the use of raw strings in Python 3.6+.
This was discovered when performing Flake8 analysis on the code base and
discovering a number of [`W605`][2] warnings thrown.
Due to the fact that, eventually, this will transition from
`DeprecationWarning` to `SyntaxError` this change set resolves all
outstanding `W605` warnings with no other changes made.
Subsequently, as a number if issues have been raised which involve
encoding issues with Unicode and marshalling between strings and bytes
(e.g. #541, #551, #556, #595) some of these regular expression strings
may _also_ need to be changed to [byte literals][3] (i.e. prefixing the
string with …
> Fix deprecated regex escape sequences in strings

- puddletag
Contrary to X11, with Wayland a app/window is no longer able to directly provide a window icon as a bitmap. Instead it will look up the `.desktop` file and use its `Icon=` value (if any). The desktop file name, if not explicitly defined, is determined from the name of the executable; in case of python apps like puddletag this is `python3`. To make it use the right one, simply explicitly set the desktop file name.
This has another downside: The `.desktop` files are only searched in specific directories. If you run puddletag straight from git/source, the desktop file won't be in a directory that will be searched in, and the icon will still be missing. Oh, brave new world.
> Fix window icon under Wayland

- puddlestuff/tagsources/discogs.py
Fixes #755 
In [puddletag/puddlestuff/tagsources/discogs.py](https://github.com/puddletag/puddletag/blob/master/puddlestuff/tagsources/discogs.py), add `global __reference_time` in `urlopen()` function definition (line 242)
> fix __reference_time global variable error in discogs.py

- puddlestuff/audioinfo/vorbis.py
Expose the "vendor string" from the vorbis comment header as a new `__vendorstring` metatag.
Fixes #785
> Expose the vorbis comment vendor string

- puddlestuff/audioinfo/apev2.py
The bytes-operations on read and write weren't properly migrated from python v2 to v3, and thus failed. Existing cover art was discarded on read, and an exception thrown on write; both work now.
The restriction to only delete APEValues with kind 0 (Text) means it was impossible to delete cover art which has kind 1 (Binary). Not really sure what the reason for that restriction was, but it's from the time before cover art was supported. External values are still excluded since I am not sure how they work in puddletag (if at all).
Fixes #663
> Fix cover art for APEv2

- puddlestuff/functions.py
- puddlestuff/helperwin.py
- puddlestuff/masstag/__init__.py
- puddlestuff/plugins/view_all_fields/__init__.py
- puddlestuff/puddleobjects.py
There are two nearly identical implementations, a leftover artefact from the py3 migration. Reduced them to one, and fixed/simplified some calling code along the way.
The case-sensitivity behaves a bit weird, because it only changes the sorting of strings that only differ in case.
Case-sensitive will always put the lowercase variant first. `AC, ab, aa, AA, ac` becomes `aa, AA, ab, ac, AC`, `aa` and `ac` come before `AA` and `AC` respectively, but in general uppercase and lowercase is still mixed.
Case-insensitive works more or less the same, but instead of putting the lowercase-variant always first it preserves the original order. The same `AC, ab, aa, AA, ac` becomes `aa, AA, ab, AC, ac`, `aa` and `AC` come before `AA` and `ac` respectively because they were originally in that order.
On …
> Improve natural sorting

- puddlestuff/audioinfo/mp4.py
- puddlestuff/audioinfo/util.py
- puddlestuff/puddleobjects.py
Replace the now deprecated imghdr module with QMimeDatabase, and also remove any hardcoded mimetype setting with a proper detection.
Fixes #786
> Fix image mimetype

- puddlestuff/functions.py
Depending on the file content type, `read()` returns either `bytes` or `str`, but `decode()` only works for `bytes`. Open the file always in textmode (so `read()` always return `str`) and let python handle the decoding, soft-failing on any decoding errors.
Fixes #806
> Fix "Import text file" function

- puddlestuff/puddleobjects.py
Properly shortcircuit the progress window when there is nothing to do.
Fixes #620
> Fix progress window with no-ops

- puddlestuff/masstag/__init__.py
- puddlestuff/masstag/dialogs.py
The two percentages are stored internally as float in the range 0 to 1, but the QSpinBox used in the UI can only do int, so the value is multiplied by 100 to bring it into the range of 0 to 100. But float times int is still float, it requires an explicit cast.
When there are no files or no profiles, simply shortcircuit instead of a hard-exit with an assertion failure.
Fixes #720
> Fix masstag coredump

- console
- puddlestuff/action_shortcuts.py
- puddlestuff/audio_filter.py
- puddlestuff/audioinfo/apev2.py
- puddlestuff/audioinfo/id3.py
- puddlestuff/audioinfo/mp4.py
- puddlestuff/audioinfo/util.py
- puddlestuff/audioinfo/vorbis.py
- puddlestuff/audioinfo/wma.py
- puddlestuff/duplicates/algwin.py
- puddlestuff/duplicates/matchfuncs.py
- puddlestuff/functions.py
- puddlestuff/helperwin.py
- puddlestuff/libraries/quodlibetlib.py
- puddlestuff/mainwin/artwork.py
- puddlestuff/mainwin/releasewidget.py
- puddlestuff/mainwin/tagpanel.py
- puddlestuff/masstag/__init__.py
- puddlestuff/puddleobjects.py
- puddlestuff/puddlesettings.py
- puddlestuff/puddletag.py
- puddlestuff/shortcutsettings.py
- puddlestuff/tagmodel.py
- puddlestuff/tagsources/__init__.py
- puddlestuff/tagsources/amg.py
- puddlestuff/tagsources/example.py
- puddlestuff/tagsources/freedb.py
- puddlestuff/tagsources/mp3tag/__init__.py
- puddlestuff/tagsources/musicbrainz.py
- puddletag
Python 2 is dead and we don't support it anymore, so out goes the dead code.
This ain't C.
You can freely split the content of parenthesis across lines, no need to use backslashes.
Dead code is dead.
Creating properties using annotations has multiple advantages:
* They completely wrap/abstract/hide the functions, making it hard to call them directly (even internally), naturally guiding you to use it as a property.
* They directly attached to the functions, keeping things together. No more creating properties with functions defined 300 lines above. 
* They enforce their own name convention, in that the functions must have the same name as the property.
* Tools seem to understand annotation-based properties easier/better, e.g. tracking the read-/write-usages.
These two variables/functions …
> Some code cleanup

- puddlestuff/puddleobjects.py
Unfortunetly QCollator can only handle plain strings, not string lists or tuples like the python sorting. So convert the list of strings into a single string by joining the elements using a separator that's unlikely to appear in the elements: the ascii unit separator.
Fixes #816
> Fix multi-value sort

- puddlestuff/audioinfo/util.py
- puddlestuff/findfunc.py
- puddlestuff/mainwin/funcs.py
Before passing a field to a function, merge all of its value using the already in the UI used separator `\\`. Also split the return-value from the function into multiple values if necessary.
Fixes #818
Fixes #825
> Properly pass multi-value fields to/from functions

- puddlestuff/masstag/dialogs.py
With the import reorg in 97f5aae5, the `set_status` function wasn't overwritten anymore, because the latter import of the `masstag` function shadowed the earlier import of the module with the same name.
Fixes #832
> Fix masstagger gui log output

- puddlestuff/audioinfo/util.py
Bugfix for something I broke with #858. Only join multi-value fields if they are strings. As it turns out, these can also be lists of dicts, for example for images.
> Fix error on multi-value join

- puddlestuff/audioinfo/util.py
- puddlestuff/data/menus
- puddlestuff/data/shortcuts
- puddlestuff/loadshortcuts.py
- puddlestuff/tagmodel.py
There are multiple fields that store different parts of the filepath, like `__filename` and `__dirname`. With a real `MockTag` (like in non-preview mode) these fields are passed to the matching properties of the `MockTag` class, which in turn all (sometimes with some indirection) read/write from/to a single attribute named `__filepath`, which contains the absolute path of the file. This also means that writing one of the fields will automatically update all the others.
The preview doesn't have these properties/attribute, it is just a dict. And it wasn't treating these fields special, and didn't update the related fields. This is the reason why for example the `__filename` field, which is displayed in the table or tag panel, still showed the original value after you used the "tag to …
> Fix filepath changes in preview mode

- puddlestuff/audioinfo/constants.py
- puddlestuff/audioinfo/id3.py
- puddlestuff/audioinfo/mp4.py
Because they are integer fields, they require special convertion. Might as well properly map them and use human-understandable names.
Fixes #850 
Nothing itunes-specific about the TSO2 frame, which is also not albumsort but albumartistsort. So rename it and use the proper name (which is already used for mp4 and wma).
Fixes #284
> Fix iTunes stuff in MP4 and ID3

- puddlestuff/puddleobjects.py
~~~
Traceback (most recent call last):
File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 657, in getfiles
dirname, subs, fnames = next(os.walk(f))
^^^^^^^^^^^^^^^^
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 2418, in run
self.retval = self.command()
^^^^^^^^^^^^^^
File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/puddleobjects.py", line 875, in threadfunc
temp = next(f)
^^^^^^^
File "/home/user/.data/miniconda3/envs/puddletag/lib/python3.12/site-packages/puddlestuff/tagmodel.py", line 1905, in load_dir …
> Fix RuntimeError in puddleobjects.py by swallowing StopIteration exception

- puddlestuff/tagsources/__init__.py
> fix typo on exception string .format in exception handler

- puddlestuff/audioinfo/mp4.py
- puddlestuff/audioinfo/util.py
- puddlestuff/mainwin/tagsources.py
- puddlestuff/mainwin/teststuff.py
- puddlestuff/puddleobjects.py
- puddlestuff/tagmodel.py
- puddlestuff/tagsources/parse_html.py
- puddlestuff/util.py
Some isinstance calls checked multiple times for the same type, caused by the automated py2->py3 conversion. Doesn't really make a functional difference, it's mostly cosmetic aka code style.
The worker function calls a non-thread-safe method of the model, which can result in a segfault. Qt provides "queued connections" for these cases to allow making such calls in a thread-safe way. Signals are one way to employ them, but they require a bit more boilerplate; for example a QObject instance to emit them. It is easier in this case to make the function call using `invokeMethod`, which will automatically "do the right thing" to make that call in a thread-safe way. While signals work
with implicit slots, in this case you need an explicit one which can simply be done with an decorator.
For more …
> Fix delete file segfault

- puddlestuff/puddleobjects.py
[PEP-585](https://peps.python.org/pep-0585/) is only available since python 3.9, it is still best to use the typing module in order to stay backwards compatible with pre-3.9.
Fixes #917
> Fix typing

- README.md
This will cover both NixOS users and those who opted in using just the Nix package manager.
> Add Nix and NixOS installation steps to README.md

- puddlestuff/audio_filter.py
After expanding the pyparsing `*` import in 7b2a73e8, `ParserException` is no longer imported. This leads to a crash when hitting that codepath.
Fixes #929
> Fix filter crash

- docs/_sources/download.txt
- docs/download.html
- docsrc/download.txt
Just a minor tweak to the docs. I wasn't sure which file is the "single source of truth" so I edited them all...
Also I wasn't sure how to best note the additional/optional "qtwayland5" wayland package? Obviously it's only a dependency if using wayland and even then, it seemed to work fine without it. On Debian 12/Bookworm it just removes this warning/error message:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
```
> minor documentation tweak - update dependency install for modern debian/ubuntu

- puddletag.desktop
I added some keywords to the `.desktop` entry to improve findability of the application.  
I also added the `FileTools` category because i thought that would be adequate for this.
<br>
- https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
- https://specifications.freedesktop.org/menu-spec/latest/apa.html & https://specifications.freedesktop.org/menu-spec/latest/apas02.html
> Add keywords to .desktop entry to improve findability

- puddlestuff/tagmodel.py
With X11 (either native or XWayland) there are no drop events triggered if there is nothing dropped, while with native Wayland they are. So check and short circuit in that case, to ensure the assumptions the called code has.
Fixes #951
> Fix empty drop on wayland

- puddlestuff/puddletag.py
- puddlestuff/tagmodel.py
Change the field-index map `TagTable.columns` (which can suffer from collapsed/overlapping keys) into a index-field map, adjusting all usages accordingly. Also convert it into a property on top of `headerdata`, removing the duplicate data and making them guaranteed in-sync.
Fixes #952
Possibly also #958
> Fix columns with same tag field

- puddlestuff/mainwin/releasewidget.py
Not sure if something changed since 26eda69b, or if it was just broken the whole time.
Fixes #984
> Fix wrong signal datatype in tag source widget
